version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.14.0-alpine
    restart: on-failure
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nextcloud:
    image: nextcloud:24.0.2-apache
    restart: on-failure
    ports:
      - ${HTTP_PORT}:80
    links:
      - postgres
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./images/postgres/multiple-databases:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES

  mongodb:
    image: mongo:4.2
    restart: on-failure
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - ${MONGODB_UI_PORT}:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_URL

  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - ${ADGUARDHOME_PORT_1}:3000
      - ${ADGUARDHOME_PORT_2}:53/udp
      - ${ADGUARDHOME_PORT_2}:53/tcp
    volumes:
      - adguardhome:/opt/adguardhome/

  nginx:
    image: nginx:1.20-alpine
    restart: always
    volumes:
      - ./images/nginx/conf/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/nginx/certs/
    network_mode: host

  auto-update:
    image: python:3.7-alpine
    restart: always
    command: sh -c "pip install requests && python3 cfautoupdater.py"
    working_dir: /var/www/cloudflare-ip/
    volumes:
      - ./images/cloudflare-ip/:/var/www/cloudflare-ip/
    network_mode: host

  speedtest:
    image: openspeedtest/latest:speedtest
    restart: always
    ports:
      - "${SPEEDTEST_PORT}:3000"

volumes:
  portainer_data:
  nextcloud:
  postgres:
  mongodb:
  adguardhome:
