version: "3.8"

services:
  auto-update:
    image: python:3.7-alpine
    restart: on-failure
    command: sh -c "pip install requests && python3 cfautoupdater.py"
    working_dir: /var/www/cloudflare-ip/
    volumes:
      - ./images/cloudflare-ip/:/var/www/cloudflare-ip/
    network_mode: host
